version: "3.9"

services:
  backend:
    build: ./studymate-backend
    container_name: studymate-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./studymate-frontend
    container_name: studymate-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend